import os
import re
import shutil
import uuid
import yaml
from datetime import datetime, timezone

from src.validators import validate_safe_id, safe_path_join
from src.utils import atomic_yaml_write, FileLock


class ProjectStateManager:
    """Manages project lifecycle and state as YAML files."""

    def __init__(self, data_dir: str = "./company_data", workspace_root: str | None = None):
        self.data_dir = data_dir
        self.projects_dir = os.path.join(data_dir, "projects")
        default_workspace_root = os.path.join(os.path.dirname(os.path.abspath(data_dir)), "projects")
        self.workspace_root = os.path.abspath(workspace_root or default_workspace_root)

    def _ensure_dirs(self, project_id: str) -> str:
        validate_safe_id(project_id, "project_id")
        project_path = safe_path_join(self.projects_dir, project_id)
        for subdir in ["ideas", "specs", "designs", "artifacts"]:
            os.makedirs(os.path.join(project_path, subdir), exist_ok=True)
        return project_path

    @staticmethod
    def _slugify_project_name(name: str) -> str:
        slug = re.sub(r"[^a-zA-Z0-9]+", "-", (name or "").strip().lower()).strip("-")
        return slug or "project"

    def _seed_project_templates(self, project_path: str, project_data: dict) -> None:
        """Create project-level template files for planning, meetings, and activation."""
        project_name = project_data.get("name", "Project")
        workspace_path = project_data.get("workspace_path", "")

        # Only include workspace README if workspace_path is a real directory.
        # An empty or missing workspace_path would resolve to a relative "README.md"
        # written to the process CWD — which is never correct.
        include_readme = bool(workspace_path and os.path.isabs(workspace_path))

        templates = {
            os.path.join(project_path, "specs", "00_stakeholder_meeting_summary.md"): (
                f"# Stakeholder Meeting Summary: {project_name}\n\n"
                "## Participants\n"
                "- Chairman\n"
                "- CEO\n"
                "- Specialists involved\n\n"
                "## Objectives\n"
                "- Document business goals and constraints.\n"
                "- Capture timeline, budget, and quality expectations.\n\n"
                "## Decisions\n"
                "- Decision 1:\n"
                "- Decision 2:\n\n"
                "## Open Questions\n"
                "-\n"
            ),
            os.path.join(project_path, "specs", "01_full_execution_plan.md"): (
                f"# Full Execution Plan: {project_name}\n\n"
                "## Scope\n"
                "- Problem statement:\n"
                "- Deliverables:\n\n"
                "## Architecture\n"
                "- System components:\n"
                "- Data flow:\n\n"
                "## Implementation Waves\n"
                "1. Planning\n"
                "2. Build\n"
                "3. Test\n"
                "4. Release\n\n"
                "## Risks and Mitigations\n"
                "-\n\n"
                "## Validation Checklist\n"
                "- [ ] Functional checks\n"
                "- [ ] Security checks\n"
                "- [ ] Performance checks\n"
            ),
            os.path.join(project_path, "artifacts", "02_activation_guide.md"): (
                f"# Activation Guide: {project_name}\n\n"
                "## Output Location\n"
                f"- Workspace path: `{workspace_path}`\n\n"
                "## Setup\n"
                "1. Install dependencies.\n"
                "2. Configure environment variables.\n"
                "3. Run local verification checks.\n\n"
                "## Run\n"
                "1. Start the application.\n"
                "2. Verify expected endpoints/pages.\n\n"
                "## Deploy\n"
                "1. Push to GitHub (if enabled).\n"
                "2. Deploy to Vercel (if connector configured).\n\n"
                "## Rollback\n"
                "1. Revert to previous commit.\n"
                "2. Redeploy stable version.\n"
            ),
            os.path.join(project_path, "artifacts", "03_project_handoff.md"): (
                f"# Project Handoff: {project_name}\n\n"
                "## Final Summary\n"
                "- What was built:\n"
                "- Key tradeoffs:\n\n"
                "## Files and Modules\n"
                "-\n\n"
                "## Operational Notes\n"
                "- Monitoring:\n"
                "- Known limitations:\n"
            ),
        }

        if include_readme:
            templates[os.path.join(workspace_path, "README.md")] = (
                f"# {project_name}\n\n"
                "This workspace was generated by COMPaaS.\n\n"
                "Use this folder for implementation outputs tied to the matching company_data project.\n"
            )

        for path, content in templates.items():
            if os.path.exists(path):
                continue
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(content)

    def create_project(
        self,
        name: str,
        description: str,
        project_type: str = "general",
        workspace_path: str = "",
        delivery_mode: str = "local",
        github_repo: str = "",
        github_branch: str = "master",
    ) -> str:
        for _ in range(10):
            project_id = str(uuid.uuid4())[:8]
            if not os.path.exists(os.path.join(self.projects_dir, project_id)):
                break
        else:
            raise RuntimeError("Failed to generate a unique project ID after 10 attempts.")
        project_path = self._ensure_dirs(project_id)
        now = datetime.now(timezone.utc).isoformat()
        workspace_slug = self._slugify_project_name(name)
        candidate_workspace = os.path.abspath(
            workspace_path or os.path.join(self.workspace_root, f"{workspace_slug}-{project_id}")
        )
        root_prefix = self.workspace_root.rstrip(os.sep) + os.sep
        if candidate_workspace != self.workspace_root and not candidate_workspace.startswith(root_prefix):
            candidate_workspace = os.path.join(self.workspace_root, f"{workspace_slug}-{project_id}")
        resolved_workspace = os.path.abspath(candidate_workspace)
        os.makedirs(resolved_workspace, exist_ok=True)

        project_data = {
            "id": project_id,
            "name": name,
            "description": description,
            "type": project_type,
            "tags": [],
            "status": "planning",
            "created_at": now,
            "updated_at": now,
            "phases": [],
            "team": [],
            "workspace_path": resolved_workspace,
            "delivery_mode": "github" if str(delivery_mode).strip().lower() == "github" else "local",
            "github_repo": str(github_repo or "").strip(),
            "github_branch": str(github_branch or "master").strip() or "master",
        }

        atomic_yaml_write(os.path.join(project_path, "project.yaml"), project_data)

        # Initialize empty task board and decision log
        atomic_yaml_write(os.path.join(project_path, "tasks.yaml"), {"tasks": []})
        atomic_yaml_write(os.path.join(project_path, "decisions.yaml"), {"decisions": []})
        self._seed_project_templates(project_path, project_data)

        return project_id

    def get_project(self, project_id: str) -> dict | None:
        try:
            validate_safe_id(project_id, "project_id")
        except ValueError:
            return None
        path = safe_path_join(self.projects_dir, project_id, "project.yaml")
        if not os.path.exists(path):
            return None
        with open(path) as f:
            return yaml.safe_load(f)

    def update_project(self, project_id: str, updates: dict) -> bool:
        try:
            validate_safe_id(project_id, "project_id")
        except ValueError:
            return False
        path = safe_path_join(self.projects_dir, project_id, "project.yaml")
        if not os.path.exists(path):
            return False
        with FileLock(path):
            with open(path) as f:
                data = yaml.safe_load(f)
            data.update(updates)
            data["updated_at"] = datetime.now(timezone.utc).isoformat()
            atomic_yaml_write(path, data)
        return True

    def _workspace_path_allowed(self, workspace_path: str) -> bool:
        root = os.path.realpath(self.workspace_root)
        candidate = os.path.realpath(workspace_path)
        if candidate == root:
            return False
        return candidate.startswith(root.rstrip(os.sep) + os.sep)

    def delete_project(self, project_id: str) -> dict | None:
        """Hard-delete a project record directory and its workspace when safe."""
        validate_safe_id(project_id, "project_id")
        project = self.get_project(project_id)
        if not isinstance(project, dict):
            return None

        project_path = safe_path_join(self.projects_dir, project_id)
        project_deleted = False
        if os.path.exists(project_path):
            shutil.rmtree(project_path)
            project_deleted = True

        workspace_deleted = False
        workspace_path = str(project.get("workspace_path", "") or "").strip()
        workspace_skip_reason = ""
        if workspace_path:
            resolved_workspace = os.path.realpath(os.path.abspath(workspace_path))
            if self._workspace_path_allowed(resolved_workspace):
                if os.path.exists(resolved_workspace):
                    shutil.rmtree(resolved_workspace)
                    workspace_deleted = True
                else:
                    workspace_skip_reason = "Workspace path did not exist."
            else:
                workspace_skip_reason = "Workspace path is outside allowed workspace root."

        return {
            "project_id": project_id,
            "project_deleted": project_deleted,
            "workspace_deleted": workspace_deleted,
            "workspace_path": workspace_path,
            "workspace_skip_reason": workspace_skip_reason,
        }

    def list_projects(self) -> list[dict]:
        if not os.path.exists(self.projects_dir):
            return []
        projects = []
        for pid in sorted(os.listdir(self.projects_dir)):
            if pid.startswith("."):
                continue
            try:
                validate_safe_id(pid, "project_id")
            except ValueError:
                continue
            pfile = safe_path_join(self.projects_dir, pid, "project.yaml")
            if not os.path.exists(pfile):
                continue
            try:
                with open(pfile) as f:
                    data = yaml.safe_load(f)
                if not data:
                    continue
                projects.append({
                    "id": data["id"],
                    "name": data["name"],
                    "description": data.get("description", ""),
                    "status": data["status"],
                    "type": data.get("type", "general"),
                    "tags": data.get("tags", []) or [],
                    "created_at": data.get("created_at", ""),
                    "updated_at": data.get("updated_at", ""),
                    "phases": data.get("phases", []) or [],
                    "team": data.get("team", []) or [],
                    "workspace_path": data.get("workspace_path", ""),
                    "delivery_mode": data.get("delivery_mode", "local"),
                    "github_repo": data.get("github_repo", ""),
                    "github_branch": data.get("github_branch", "master"),
                    "run_instructions": data.get("run_instructions", ""),
                    "quality_latest": data.get("quality_latest", {}),
                    "quality_updated_at": data.get("quality_updated_at", ""),
                })
            except (yaml.YAMLError, KeyError, OSError):
                continue
        return projects
