import type { PromptExample, PromptExampleCategory } from '../types';

export const PROMPT_EXAMPLE_CATEGORIES: PromptExampleCategory[] = [
  'Productivity',
  'Finance',
  'Health',
  'Education',
  'Community',
  'Business',
  'AI + Design',
  'AI + Lifestyle',
  'Creator',
  'Commerce',
  'Product Ops',
  'Maps + Data',
  'Creative Tech',
];

export const PROMPT_EXAMPLES: PromptExample[] = [
  {
    id: 'task-manager',
    category: 'Productivity',
    label: 'Task Manager',
    prompt: 'Make a minimalist task manager where users can create projects, set deadlines, and track task status. Include priority tags and a focused daily view. Use a clean and distraction-free interface.',
    keywords: ['tasks', 'project', 'deadline', 'priority', 'daily'],
  },
  {
    id: 'smart-calendar',
    category: 'Productivity',
    label: 'Smart Calendar',
    prompt: 'Build a smart calendar app that suggests optimal time slots for tasks based on availability. Include drag-and-drop scheduling and color-coded categories. Keep the design modern and simple.',
    keywords: ['calendar', 'scheduling', 'drag and drop', 'time slots'],
  },
  {
    id: 'notes-hub',
    category: 'Productivity',
    label: 'Notes Hub',
    prompt: 'Create a note-taking app with folders, tags, and quick search. Allow markdown support and pinned notes. Use a calm, productivity-oriented layout.',
    keywords: ['notes', 'markdown', 'folders', 'search'],
  },
  {
    id: 'budget-tracker',
    category: 'Finance',
    label: 'Budget Tracker',
    prompt: 'Build a personal budget app where users can track income and expenses by category. Include visual charts and monthly summaries. Use a clear financial dashboard style design.',
    keywords: ['budget', 'income', 'expenses', 'charts', 'finance'],
  },
  {
    id: 'portfolio-tracker',
    category: 'Finance',
    label: 'Portfolio Tracker',
    prompt: 'Create an investment portfolio tracker that displays asset allocation and performance over time. Include alerts for price changes. Keep the interface professional and data-focused.',
    keywords: ['investments', 'assets', 'performance', 'alerts'],
  },
  {
    id: 'subscriptions',
    category: 'Finance',
    label: 'Subscriptions',
    prompt: 'Make a subscription management app that tracks recurring payments and renewal dates. Include reminder notifications and yearly cost breakdown. Use a clean and organized layout.',
    keywords: ['subscription', 'payments', 'renewal', 'reminders'],
  },
  {
    id: 'workout-planner',
    category: 'Health',
    label: 'Workout Planner',
    prompt: 'Create a workout planner where users can build routines, log exercises, and track progress. Include progress charts and goal milestones. Use an energetic and motivating design.',
    keywords: ['workout', 'fitness', 'progress', 'goals'],
  },
  {
    id: 'meal-planner',
    category: 'Health',
    label: 'Meal Planner',
    prompt: 'Build a meal planning app that lets users create weekly menus and generate shopping lists. Include calorie estimates and dietary filters. Keep the layout fresh and easy to navigate.',
    keywords: ['meal', 'nutrition', 'shopping list', 'calories'],
  },
  {
    id: 'sleep-tracker',
    category: 'Health',
    label: 'Sleep Tracker',
    prompt: 'Make a sleep tracker app where users log sleep hours and quality. Include trends over time and improvement tips. Use a calming and night-themed interface.',
    keywords: ['sleep', 'health', 'trends', 'tracker'],
  },
  {
    id: 'language-coach',
    category: 'Education',
    label: 'Language Coach',
    prompt: 'Build a language learning app with daily lessons, quizzes, and spaced repetition. Include progress tracking and achievement badges. Use a friendly and engaging design.',
    keywords: ['language', 'lessons', 'quizzes', 'spaced repetition'],
  },
  {
    id: 'study-planner',
    category: 'Education',
    label: 'Study Planner',
    prompt: 'Create a study planner for students to organize subjects, assignments, and exams. Include countdown timers and revision reminders. Use a structured and academic layout.',
    keywords: ['study', 'students', 'assignments', 'exam'],
  },
  {
    id: 'flashcards',
    category: 'Education',
    label: 'Flashcards',
    prompt: 'Make a flashcard app with customizable decks and test modes. Include spaced repetition and performance analytics. Keep the design simple and focused on learning.',
    keywords: ['flashcard', 'decks', 'test mode', 'learning'],
  },
  {
    id: 'local-events',
    category: 'Community',
    label: 'Local Events',
    prompt: 'Build a local events discovery app where users can browse events by category and location. Include RSVP functionality and map integration. Use a vibrant and community-driven design.',
    keywords: ['events', 'rsvp', 'maps', 'community'],
  },
  {
    id: 'hobby-groups',
    category: 'Community',
    label: 'Hobby Groups',
    prompt: 'Create a hobby-based community app where users join groups, share posts, and chat. Include profile pages and activity feeds. Keep the interface modern and social-focused.',
    keywords: ['community', 'groups', 'posts', 'chat'],
  },
  {
    id: 'goal-sharing',
    category: 'Community',
    label: 'Goal Sharing',
    prompt: 'Make a goal-sharing app where users set public goals and track progress with friends. Include comments and encouragement features. Use an inspiring and clean layout.',
    keywords: ['goals', 'friends', 'progress', 'social'],
  },
  {
    id: 'smb-dashboard',
    category: 'Business',
    label: 'SMB Dashboard',
    prompt: 'Create a dashboard for small business owners that tracks revenue, expenses, and customer growth. Include charts, filters, and the ability to export reports. Use a clear and professional layout.',
    keywords: ['business', 'dashboard', 'revenue', 'reports'],
  },
  {
    id: 'kids-math-game',
    category: 'Education',
    label: 'Kids Math Game',
    prompt: 'Build a web-based game that helps kids practice math skills through interactive challenges. Include levels, progress tracking, and rewards for completing tasks. Make it colorful and engaging.',
    keywords: ['math', 'kids', 'game', 'levels'],
  },
  {
    id: 'onboarding-portal',
    category: 'Business',
    label: 'Onboarding Portal',
    prompt: 'Design an onboarding portal that guides new employees through key company policies, values, and team introductions. Make it welcoming, interactive, and easy to follow.',
    keywords: ['onboarding', 'employees', 'policies', 'portal'],
  },
  {
    id: 'room-styler-ai',
    category: 'AI + Design',
    label: 'Room Styler AI',
    prompt: 'Build a tool where users can upload a photo of their room and apply different interior design styles using AI. Let them save, compare, and share styled images. Use a modern and visual-first interface.',
    keywords: ['ai', 'interior design', 'image upload', 'styling'],
  },
  {
    id: 'founder-network',
    category: 'Community',
    label: 'Founder Network',
    prompt: 'Create a networking app for first-time startup founders to connect based on location, industry, and funding stage. Include profiles, messaging, and event discovery. Keep the design clean and startup-oriented.',
    keywords: ['startup', 'founders', 'networking', 'messaging'],
  },
  {
    id: 'fridge-chef-ai',
    category: 'AI + Lifestyle',
    label: 'Fridge Chef AI',
    prompt: 'Create an AI-powered tool where users can specify what they have in their fridge and receive recipe recommendations. Style the app like a retro restaurant menu with elegant colors and fonts.',
    keywords: ['ai', 'recipes', 'food', 'fridge'],
  },
  {
    id: 'photo-portfolio',
    category: 'Creator',
    label: 'Photo Portfolio',
    prompt: 'Create a personal portfolio website for a photographer with an About Me section and a gallery to showcase work. Make the entire website black and white with a simple and minimal interface.',
    keywords: ['portfolio', 'photographer', 'gallery', 'minimal'],
  },
  {
    id: 'link-in-bio',
    category: 'Creator',
    label: 'Link-in-Bio',
    prompt: 'Make a link-in-bio app that presents all social accounts in an intuitive and aesthetic interface. Use a random image as a placeholder profile picture for now.',
    keywords: ['links', 'social', 'profile', 'creator'],
  },
  {
    id: 'kpi-dashboard',
    category: 'Business',
    label: 'KPI Dashboard',
    prompt: 'Create a data-driven dashboard that helps users monitor business KPIs over time. Use clear hierarchy, structured layouts, and realistic sample data and KPIs.',
    keywords: ['kpi', 'analytics', 'dashboard', 'business'],
  },
  {
    id: 'e-commerce',
    category: 'Commerce',
    label: 'E-Commerce',
    prompt: 'Build a responsive e-commerce experience for browsing and purchasing products. Include product listings, product detail pages, and a checkout flow. Use a modern and trustworthy design.',
    keywords: ['commerce', 'products', 'checkout', 'store'],
  },
  {
    id: 'roadmap-planner',
    category: 'Product Ops',
    label: 'Roadmap Planner',
    prompt: 'Make a roadmap planning tool where product managers can create and visualize quarterly roadmaps. Include draggable initiative cards, priority tags, and color coding by team. Design it with a professional timeline view and clean UI.',
    keywords: ['roadmap', 'product', 'timeline', 'planning'],
  },
  {
    id: 'landmark-mapper',
    category: 'Maps + Data',
    label: 'Landmark Mapper',
    prompt: 'Make an app that displays a map of local landmarks based on the current visible map area. Use Wikipedia as the data source for landmarks.',
    keywords: ['maps', 'wikipedia', 'landmarks', 'geodata'],
  },
  {
    id: 'habit-tracker',
    category: 'Productivity',
    label: 'Habit Tracker',
    prompt: 'Make a personal habit tracker where users can set daily or weekly habits, log completions, and view streaks. Include progress bars and motivational messages. Use a clean, goal-focused layout.',
    keywords: ['habits', 'streaks', 'goals', 'tracker'],
  },
  {
    id: 'synth-lab',
    category: 'Creative Tech',
    label: 'Synth Lab',
    prompt: 'Create an interactive synthesizer system inspired by tools like the Teenage Engineering OP-1. Focus on motion, tactile user feedback, and high-quality sound design.',
    keywords: ['synth', 'music', 'audio', 'interactive'],
  },
];
